import { resend } from "./email-provider";

interface SendConsultationEmailInput {
  name: string;
  phone: string;
  email?: string;
  city?: string;
  consultationType: string;
  preferredDate?: Date;
  preferredTime?: string;
  message?: string;
}

const businessEmail = process.env.BUSINESS_EMAIL;

if (!businessEmail) {
  throw new Error(
    "BUSINESS_EMAIL is not configured"
  );
}

const formatDate = (date?: Date) => {
  if (!date) {
    return "Not provided";
  }

  return new Intl.DateTimeFormat("en-IN", {
    dateStyle: "medium",
  }).format(new Date(date));
};

export const sendConsultationEmail = async (
  consultation: SendConsultationEmailInput
) => {
  const {
    name,
    phone,
    email,
    city,
    consultationType,
    preferredDate,
    preferredTime,
    message,
  } = consultation;

  const { data, error } =
    await resend.emails.send({
      from:
        process.env.EMAIL_FROM ||
        "onboarding@resend.dev",
      to: [businessEmail],
      subject: `New Consultation Request - ${name}`,
      html: `
        <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #24231f;">
          <h2 style="margin-bottom: 20px;">
            New Consultation Request
          </h2>

          <p>
            A new consultation request has been submitted
            through your interior design website.
          </p>

          <hr style="margin: 20px 0; border: none; border-top: 1px solid #ddd;" />

          <h3>Customer Details</h3>

          <p>
            <strong>Name:</strong>
            ${name}
          </p>

          <p>
            <strong>Phone:</strong>
            ${phone}
          </p>

          <p>
            <strong>Email:</strong>
            ${email || "Not provided"}
          </p>

          <p>
            <strong>City:</strong>
            ${city || "Not provided"}
          </p>

          <h3>Consultation Details</h3>

          <p>
            <strong>Consultation Type:</strong>
            ${consultationType}
          </p>

          <p>
            <strong>Preferred Date:</strong>
            ${formatDate(preferredDate)}
          </p>

          <p>
            <strong>Preferred Time:</strong>
            ${preferredTime || "Not provided"}
          </p>

          <p>
            <strong>Message:</strong>
          </p>

          <p>
            ${message || "No message provided"}
          </p>

          <hr style="margin: 20px 0; border: none; border-top: 1px solid #ddd;" />

          <p style="font-size: 13px; color: #666;">
            This email was automatically generated by your
            interior design website.
          </p>
        </div>
      `,
    });

  if (error) {
    throw new Error(
      `Failed to send consultation email: ${error.message}`
    );
  }

  return data;
};
